apiVersion: v1
kind: Pod
metadata:
  name: mon-pod
  labels:
    app: multi-container-pod
spec:
  containers:
  - name: httpd
    image: httpd:latest
    ports:
    - containerPort: 80
  - name: busybox
    image: busybox:latest
    command: ['sh', '-c', 'echo Hello from busybox && sleep 3600']