apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: mypod-container
    image: nginx
    volumeMounts:
    - mountPath: "/usr/share/nginx/html"
      name: mypvc
  volumes:
  - name: mypvc
    persistentVolumeClaim:
      claimName: my-pvc
